---
- name: Run Flask app locally with Docker + Nginx reverse proxy
  hosts: localhost
  connection: local
  become: true

  tasks:
    
    - name: Build Docker image (includes requirements.txt)
      docker_image:
        name: resume-app
        source: build
        build:
          path: ../    # because playbook is inside ansible/ folder

    - name: Run Flask container
      docker_container:
        name: resume-app-container
        image: resume-app
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Add reverse proxy config
      copy:
        dest: /etc/nginx/sites-available/resume
        content: |
          server {
              listen 80;
              server_name localhost;

              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable reverse proxy config
      file:
        src: /etc/nginx/sites-available/resume
        dest: /etc/nginx/sites-enabled/resume
        state: link
        force: true

    - name: Remove default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
